# ═══════════════════════════════════════════════════════════════════════════════
#  kite_data.py  —  Unified Data Layer for TA Terminal  v3.0
#
#  RULE:
#    ALL price / OHLCV / quote data  →  Zerodha Kite API
#    ALL fundamental / financial data →  yfinance (no Kite equivalent)
#
#  Returns DataFrames in the EXACT same format the TA modules expect:
#    Columns : Open, High, Low, Close, Volume  (capital first letter)
#    Index   : DatetimeIndex, timezone-naive
# ═══════════════════════════════════════════════════════════════════════════════

import os
import logging
import pandas as pd
import streamlit as st
from datetime import datetime, timedelta
from typing import Optional, Dict, Any
from kiteconnect import KiteConnect

logger = logging.getLogger("kite_data")


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 1 — KITE CLIENT
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_resource
def get_kite_client() -> Optional[KiteConnect]:
    """
    Returns an authenticated KiteConnect instance.

    Credential lookup order:
      1. .streamlit/secrets.toml  →  [kite] api_key + access_token
      2. Environment variables    →  KITE_API_KEY + KITE_ACCESS_TOKEN
      3. access_token.txt file    →  local dev (generated by login.py)

    Returns None if credentials unavailable (triggers yfinance fallback).
    """
    api_key      = None
    access_token = None

    # ── 1. Streamlit secrets ──────────────────────────────────────────────────
    try:
        api_key      = st.secrets["kite"]["api_key"]
        access_token = st.secrets["kite"]["access_token"]
    except Exception:
        pass

    # ── 2. Environment variables ──────────────────────────────────────────────
    if not api_key:
        api_key      = os.environ.get("KITE_API_KEY", "")
        access_token = os.environ.get("KITE_ACCESS_TOKEN", "")

    # ── 3. access_token.txt file ──────────────────────────────────────────────
    if not api_key or not access_token:
        try:
            cfg_file = "kite_config.txt"   # format: api_key\naccess_token
            if os.path.exists(cfg_file):
                lines        = open(cfg_file).read().strip().splitlines()
                api_key      = lines[0].strip()
                access_token = lines[1].strip() if len(lines) > 1 else ""
        except Exception:
            pass

    if not api_key or not access_token:
        try:
            # Legacy: just access_token.txt (need api_key from env or config)
            api_key = api_key or os.environ.get("KITE_API_KEY", "")
            if os.path.exists("access_token.txt") and api_key:
                access_token = open("access_token.txt").read().strip()
        except Exception:
            pass

    if not api_key or not access_token:
        logger.warning("Kite credentials not found — OHLCV will use yfinance fallback")
        return None

    try:
        kite = KiteConnect(api_key=api_key)
        kite.set_access_token(access_token)
        logger.info("Kite API client initialised successfully")
        return kite
    except Exception as e:
        logger.error(f"Kite client init failed: {e}")
        return None


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 2 — SYMBOL UTILITIES
# ══════════════════════════════════════════════════════════════════════════════

def parse_symbol(symbol: str) -> tuple:
    """
    Parse symbol string → (kite_symbol, exchange, yf_symbol)

    Examples:
      "RELIANCE"     → ("RELIANCE",  "NSE", "RELIANCE.NS")
      "RELIANCE.NS"  → ("RELIANCE",  "NSE", "RELIANCE.NS")
      "RELIANCE.BO"  → ("RELIANCE",  "BSE", "RELIANCE.BO")
      "NIFTY50"      → ("NIFTY 50",  "NSE", "^NSEI")
    """
    s = symbol.upper().strip()

    # yfinance suffix handling
    if s.endswith(".BO"):
        kite_sym = s[:-3]
        exchange  = "BSE"
        yf_sym    = s
    elif s.endswith(".NS"):
        kite_sym = s[:-3]
        exchange  = "NSE"
        yf_sym    = s
    else:
        kite_sym = s
        exchange  = "NSE"
        yf_sym    = s + ".NS"

    # Kite uses spaces for indices
    _index_map = {
        "NIFTY50":  ("NIFTY 50",  "NSE", "^NSEI"),
        "NIFTY":    ("NIFTY 50",  "NSE", "^NSEI"),
        "BANKNIFTY":("NIFTY BANK","NSE", "^NSEBANK"),
        "SENSEX":   ("SENSEX",    "BSE", "^BSESN"),
    }
    if kite_sym in _index_map:
        kite_sym, exchange, yf_sym = _index_map[kite_sym]

    return kite_sym, exchange, yf_sym


@st.cache_data(ttl=86400)
def get_instrument_token(_kite_key: str,
                          kite_sym: str,
                          exchange: str = "NSE") -> Optional[int]:
    """
    Look up Kite instrument token for a symbol.
    Cached for 24 hours — instrument list doesn't change intraday.

    _kite_key is passed for cache invalidation but not used directly.
    """
    kite = get_kite_client()
    if not kite:
        return None
    try:
        instruments = kite.instruments(exchange)
        for inst in instruments:
            if inst["tradingsymbol"] == kite_sym and inst["exchange"] == exchange:
                logger.info(f"Token found: {exchange}:{kite_sym} → {inst['instrument_token']}")
                return inst["instrument_token"]
        logger.warning(f"No token found for {exchange}:{kite_sym}")
        return None
    except Exception as e:
        logger.error(f"Instrument lookup failed: {e}")
        return None


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 3 — INTERVAL & PERIOD MAPPING
# ══════════════════════════════════════════════════════════════════════════════

# TA Terminal timeframe label → Kite interval string
TF_TO_KITE_INTERVAL = {
    "Daily":   "day",
    "Weekly":  "week",
    "Monthly": "month",
    "4H":      "60minute",   # Kite max intraday = 60min
    "1H":      "60minute",
    "30m":     "30minute",
    "15m":     "15minute",
    "5m":      "5minute",
    "1m":      "minute",
}

# Kite hard limits: max calendar days per interval
KITE_MAX_CALENDAR_DAYS = {
    "minute":   60,
    "3minute":  100,
    "5minute":  100,
    "10minute": 100,
    "15minute": 199,    # tested — 200 causes "interval exceeds max limit"
    "30minute": 199,
    "60minute": 399,
    "day":      2000,
    "week":     2000,
    "month":    2000,
}

# Period string → calendar days requested
PERIOD_TO_DAYS = {
    "1d":  1,
    "5d":  5,
    "1mo": 35,
    "3mo": 95,
    "6mo": 185,
    "1y":  370,
    "2y":  740,
    "5y":  1850,
    "max": 3650,
}

# yfinance interval for fallback
TF_TO_YF_INTERVAL = {
    "Daily":   "1d",
    "Weekly":  "1wk",
    "Monthly": "1mo",
    "4H":      "1h",
    "1H":      "1h",
    "30m":     "30m",
    "15m":     "15m",
    "5m":      "5m",
    "1m":      "1m",
}


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 4 — OHLCV FROM KITE  (primary source)
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=300)
def fetch_ohlcv_kite(symbol: str,
                     timeframe: str = "Daily",
                     period: str = "1y") -> pd.DataFrame:
    """
    PRIMARY DATA SOURCE — Zerodha Kite API

    Fetches OHLCV historical data and returns a DataFrame with:
      Columns : Open, High, Low, Close, Volume
      Index   : DatetimeIndex (timezone-naive)

    Automatically falls back to yfinance if:
      - Kite not configured (no credentials)
      - Symbol not found on Kite
      - Any API error occurs

    Args:
        symbol    : NSE symbol e.g. "RELIANCE", "RELIANCE.NS", "INFY.NS"
        timeframe : "Daily", "Weekly", "Monthly", "4H", "1H", "15m", "5m"
        period    : "1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "max"
    """
    kite = get_kite_client()
    if not kite:
        logger.info(f"Kite not available — using yfinance for {symbol}")
        return _yf_ohlcv(symbol, timeframe, period)

    kite_sym, exchange, yf_sym = parse_symbol(symbol)
    interval = TF_TO_KITE_INTERVAL.get(timeframe, "day")

    # Calculate safe date range within Kite limits
    days_requested = PERIOD_TO_DAYS.get(period, 370)
    days_max       = KITE_MAX_CALENDAR_DAYS.get(interval, 400)
    days_back      = min(days_requested, days_max)

    to_date   = datetime.now()
    from_date = to_date - timedelta(days=days_back)

    # Get instrument token
    token = get_instrument_token(
        str(id(kite)),   # cache key — changes if kite obj changes
        kite_sym, exchange
    )
    if not token:
        logger.warning(f"No token for {exchange}:{kite_sym} — falling back to yfinance")
        return _yf_ohlcv(symbol, timeframe, period)

    try:
        records = kite.historical_data(
            instrument_token = token,
            from_date        = from_date.strftime("%Y-%m-%d"),
            to_date          = to_date.strftime("%Y-%m-%d %H:%M:%S"),
            interval         = interval,
            continuous       = False,
            oi               = False,
        )

        if not records:
            logger.warning(f"Empty response from Kite for {symbol} — falling back")
            return _yf_ohlcv(symbol, timeframe, period)

        # Build DataFrame
        df = pd.DataFrame(records)
        df.rename(columns={"date": "Datetime"}, inplace=True)
        df.set_index("Datetime", inplace=True)

        # Ensure timezone-naive index
        if hasattr(df.index, "tz") and df.index.tz is not None:
            df.index = df.index.tz_localize(None)
        else:
            df.index = pd.to_datetime(df.index)

        # Standardise columns to capital first letter (matches yfinance format)
        df.rename(columns={
            "open":   "Open",
            "high":   "High",
            "low":    "Low",
            "close":  "Close",
            "volume": "Volume",
        }, inplace=True)

        df = df[["Open", "High", "Low", "Close", "Volume"]].dropna()
        df = df[df["Volume"] >= 0]   # remove any bad rows

        logger.info(
            f"Kite OHLCV: {exchange}:{kite_sym} | {interval} | "
            f"{len(df)} bars | {df.index[0].date()} → {df.index[-1].date()}"
        )
        return df

    except Exception as e:
        logger.error(f"Kite OHLCV fetch failed for {symbol} ({e}) — falling back to yfinance")
        return _yf_ohlcv(symbol, timeframe, period)


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 5 — LIVE QUOTE FROM KITE
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=15)   # 15-second cache for live prices
def fetch_quote_kite(symbol: str) -> Dict[str, Any]:
    """
    PRIMARY QUOTE SOURCE — Zerodha Kite API

    Returns dict with live price fields.
    Fundamental fields (PE, EPS, etc.) are NOT available from Kite
    and are therefore NOT included here — use fetch_fundamentals_yf() for those.

    Returns:
        {
          "symbol"                   : "RELIANCE",
          "exchange"                 : "NSE",
          "currentPrice"             : 2841.50,
          "previousClose"            : 2820.00,
          "open"                     : 2825.00,
          "dayHigh"                  : 2855.00,
          "dayLow"                   : 2815.00,
          "volume"                   : 4500000,
          "lastTradeTime"            : datetime,
          "regularMarketChange"      : 21.50,
          "regularMarketChangePercent": 0.76,
          "source"                   : "kite",
        }
    """
    kite = get_kite_client()
    if not kite:
        return _yf_quote(symbol)

    kite_sym, exchange, _ = parse_symbol(symbol)
    kite_key = f"{exchange}:{kite_sym}"

    try:
        quote = kite.quote([kite_key])
        q     = quote.get(kite_key, {})
        ohlc  = q.get("ohlc", {})

        ltp       = q.get("last_price", 0) or 0
        prev_close = ohlc.get("close", 0)  or 0
        change     = ltp - prev_close
        change_pct = (change / prev_close * 100) if prev_close else 0

        result = {
            "symbol":                    kite_sym,
            "exchange":                  exchange,
            "currentPrice":              ltp,
            "regularMarketPrice":        ltp,
            "previousClose":             prev_close,
            "open":                      ohlc.get("open",  0),
            "dayHigh":                   ohlc.get("high",  0),
            "dayLow":                    ohlc.get("low",   0),
            "volume":                    q.get("volume",   0),
            "lastTradeTime":             q.get("last_trade_time"),
            "regularMarketChange":       round(change,     2),
            "regularMarketChangePercent": round(change_pct, 4),
            "averagePrice":              q.get("average_price", 0),
            "buyQty":                    q.get("buy_quantity",  0),
            "sellQty":                   q.get("sell_quantity", 0),
            "source":                    "kite",
        }
        logger.info(f"Kite quote: {kite_key} = ₹{ltp}")
        return result

    except Exception as e:
        logger.error(f"Kite quote failed for {symbol}: {e}")
        return _yf_quote(symbol)


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 6 — MULTI-TIMEFRAME OHLCV FOR MODULE 10
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=300)
def fetch_multi_tf_kite(symbol: str,
                         period: str = "1y") -> Dict[str, pd.DataFrame]:
    """
    Fetches OHLCV for all 4 timeframes used in Multi-Timeframe Analysis.
    All data from Kite (falls back per-timeframe to yfinance if needed).

    Returns:
        {
          "monthly" : DataFrame,
          "weekly"  : DataFrame,
          "daily"   : DataFrame,
          "h4"      : DataFrame,  # 60min bars as 4H proxy
        }
    """
    result = {}
    tf_map = [
        ("monthly", "Monthly", "5y"),
        ("weekly",  "Weekly",  "2y"),
        ("daily",   "Daily",   period),
        ("h4",      "4H",      "6mo"),
    ]
    for key, tf_label, tf_period in tf_map:
        try:
            df = fetch_ohlcv_kite(symbol, timeframe=tf_label, period=tf_period)
            if not df.empty:
                result[key] = df
                logger.info(f"MTF {key}: {len(df)} bars")
        except Exception as e:
            logger.warning(f"MTF fetch failed {symbol} {tf_label}: {e}")

    return result


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 7 — FUNDAMENTALS FROM YFINANCE  (only source for financial data)
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=3600)   # cache for 1 hour — fundamentals don't change often
def fetch_fundamentals_yf(symbol: str) -> Dict[str, Any]:
    """
    FUNDAMENTALS SOURCE — yfinance ONLY

    Kite API does NOT provide:
      - P/E ratio, EPS, revenue, net income
      - Balance sheet, income statement, cash flow
      - Dividend yield, book value
      - Quarterly / annual earnings
      - Analyst estimates
      - Sector / industry

    This function fetches all of the above from yfinance.
    Returns the full yfinance .info dict plus structured financial tables.

    Args:
        symbol: any format — "RELIANCE", "RELIANCE.NS", "INFY.NS"
    """
    _, _, yf_sym = parse_symbol(symbol)

    try:
        import yfinance as yf
        ticker = yf.Ticker(yf_sym)
        info   = ticker.info or {}

        # Add 52W hi/lo from history if not in info
        if not info.get("fiftyTwoWeekHigh"):
            try:
                hist = ticker.history(period="1y")
                if not hist.empty:
                    info["fiftyTwoWeekHigh"] = float(hist["High"].max())
                    info["fiftyTwoWeekLow"]  = float(hist["Low"].min())
            except Exception:
                pass

        logger.info(f"yfinance fundamentals fetched for {yf_sym}: "
                    f"PE={info.get('trailingPE','N/A')} "
                    f"EPS={info.get('trailingEps','N/A')}")
        return info

    except Exception as e:
        logger.error(f"yfinance fundamentals failed for {symbol}: {e}")
        return {}


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 8 — COMBINED INFO DICT (used by app.py fetch_info)
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=60)
def fetch_combined_info(symbol: str) -> Dict[str, Any]:
    """
    Returns a single dict combining:
      - Live price fields  →  from Kite (real-time)
      - Fundamental fields →  from yfinance (hourly cache)

    Kite price data always takes precedence over yfinance price fields.
    This dict is used throughout the TA Terminal wherever info is needed.
    """
    # Get both sources
    kite_quote  = fetch_quote_kite(symbol)
    yf_info     = fetch_fundamentals_yf(symbol)

    # Start with yfinance (fundamentals base)
    combined = dict(yf_info)

    # Override price fields with Kite live data
    price_fields = [
        "currentPrice", "regularMarketPrice", "previousClose",
        "open", "dayHigh", "dayLow", "volume",
        "regularMarketChange", "regularMarketChangePercent",
        "lastTradeTime", "averagePrice",
    ]
    for field in price_fields:
        if field in kite_quote:
            combined[field] = kite_quote[field]

    # Add source tags
    combined["_price_source"]       = kite_quote.get("source", "yfinance")
    combined["_fundamentals_source"] = "yfinance"
    combined["symbol"]               = kite_quote.get("symbol", symbol)
    combined["exchange"]             = kite_quote.get("exchange", "NSE")

    return combined


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 9 — YFINANCE FALLBACKS (price only — used when Kite unavailable)
# ══════════════════════════════════════════════════════════════════════════════

def _yf_ohlcv(symbol: str, timeframe: str, period: str) -> pd.DataFrame:
    """yfinance OHLCV fallback — only used when Kite unavailable."""
    try:
        import yfinance as yf
        _, _, yf_sym = parse_symbol(symbol)
        interval = TF_TO_YF_INTERVAL.get(timeframe, "1d")
        ticker = yf.Ticker(yf_sym)
        df = ticker.history(period=period, interval=interval, auto_adjust=True)
        if df.empty:
            return pd.DataFrame()
        df.index = pd.to_datetime(df.index)
        if hasattr(df.index, "tz") and df.index.tz is not None:
            df.index = df.index.tz_localize(None)
        df = df[["Open", "High", "Low", "Close", "Volume"]].dropna()
        logger.info(f"yfinance OHLCV fallback: {yf_sym} → {len(df)} bars")
        return df
    except Exception as e:
        logger.error(f"yfinance OHLCV fallback failed: {e}")
        return pd.DataFrame()


def _yf_quote(symbol: str) -> Dict[str, Any]:
    """yfinance quote fallback — only used when Kite quote fails."""
    try:
        import yfinance as yf
        _, _, yf_sym = parse_symbol(symbol)
        info = yf.Ticker(yf_sym).info or {}
        ltp  = info.get("currentPrice") or info.get("regularMarketPrice", 0)
        prev = info.get("previousClose", 0)
        chg  = ltp - prev
        return {
            "symbol":                     symbol,
            "exchange":                   "NSE",
            "currentPrice":               ltp,
            "regularMarketPrice":         ltp,
            "previousClose":              prev,
            "open":                       info.get("open",    0),
            "dayHigh":                    info.get("dayHigh", 0),
            "dayLow":                     info.get("dayLow",  0),
            "volume":                     info.get("volume",  0),
            "regularMarketChange":        round(chg, 2),
            "regularMarketChangePercent": round(chg / prev * 100, 4) if prev else 0,
            "source":                     "yfinance",
        }
    except Exception:
        return {"currentPrice": 0, "source": "error"}


# ══════════════════════════════════════════════════════════════════════════════
#  SECTION 10 — CONVENIENCE FUNCTIONS (used in app.py)
# ══════════════════════════════════════════════════════════════════════════════

def is_kite_connected() -> bool:
    """Returns True if Kite client is available and authenticated."""
    return get_kite_client() is not None


def get_data_source_label() -> str:
    """Returns a human-readable label for the current data source."""
    if is_kite_connected():
        return "KITE LIVE"
    return "YFINANCE"
